name: Build go-server image (manual)
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        required: true
        default: "latest"
jobs:
  build-arm-images:
    strategy:
      matrix:
        label: [arm, arm66, amd64]
        include:
          - label: self-hosted
          - label: linux
    runs-on: ${{ matrix.label }}
    steps:
      - name: Build target image
        run: |
          echo "Build target image ${{ matrix.label }}"
