name: Build go-server image
on:
  release:
    types: [ created, edited ]
jobs:
  build-arm64:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tags
        id: tags
        run: |
          echo ::set-output name=arch::arm64
          echo ::set-output name=image::ghcr.io/${{ github.repository_owner }}/go-server-arm64
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}          
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          make docker
      - name: Push
        run: |
          docker push ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
  build-amd64:
    runs-on: [linux, amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tags
        id: tags
        run: |
          echo ::set-output name=arch::amd64
          echo ::set-output name=image::ghcr.io/${{ github.repository_owner }}/go-server-amd64
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}          
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          make docker
      - name: Push
        run: |
          docker push ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
