name: Build go-server image for a target architecture
on:
  workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        label: [arm, arm64, amd64]
    runs-on: ${{ matrix.label == 'amd64' && 'ubuntu-latest' || 'self-hosted, linux, ' + matrix.label }}
    steps:
      - name: build ${{ matrix.label }}
        run: |
          echo "Building image for target ${{ matrix.label }}"
