name: Build go-server image (manual)
on:
  workflow_dispatch
jobs:
  build-arm-images:
    strategy:
      matrix:
        label: [arm, arm64, amd64]
    uses: ./.github/workflows/make-image-target.yaml
    with:
      target: ${{ matrix.target }}
