name: Build go-server images (manual)
on:
  workflow_dispatch
jobs:
  var:
    name: Set variables
    runs-on: ubuntu-latest
    outputs:
      platform: "linux"
      nginx: 1.23.2
      image: ${{ steps.var.outputs.image }}
      tag: ${{ steps.var.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set variables
        id: var
        run: |
          TAG="$(git describe --tags)" && echo "tag=${TAG#v}" >> $GITHUB_OUTPUT
          echo "image=ghcr.io/${{ github.repository }}" >> $GITHUB_OUTPUT
  build:
    name: Build docker images
    needs: var
    strategy:
      matrix:
        arch: [arm, arm64, amd64]
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build \
            --tag ${{ steps.var.outputs.image }}-${{ matrix.arch }}:${{ steps.var.outputs.tag }} \
            --build-arg VERSION=${{ steps.var.outputs.nginx }} \
            --build-arg ARCH=${{ matrix.arch }} \
            --build-arg PLATFORM=${{ steps.var.outputs.platform }} \
            -f etc/docker/Dockerfile .
      - name: Push
        run: |
          docker push ${{ steps.var.outputs.image }}-${{ matrix.arch }}:${{ steps.var.outputs.tag }}
  manifest:
    name: Create docker manifest
    needs:
      - var 
      - build
    strategy:
      matrix:
        include:
          - tag: ${{ steps.var.outputs.tag }}
          - tag: latest
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Manifest
        run: |
          docker manifest create ${{ steps.var.outputs.image }}:${{ matrix.tag }} \
            --amend ${{ steps.var.outputs.image }}-amd64:${{ steps.var.outputs.tag }} \
            --amend ${{ steps.var.outputs.image }}-arm64:${{ steps.var.outputs.tag }} \
            --amend ${{ steps.var.outputs.image }}-arm:${{ steps.var.outputs.tag }}
          docker manifest annotate --arch arm64 \
            ${{ steps.tags.outputs.image }}:${{ matrix.tag  }} \
            ${{ steps.tags.outputs.image }}-arm64:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch amd64 \
            ${{ steps.tags.outputs.image }}:${{ matrix.tag  }} \
            ${{ steps.tags.outputs.manifest }}-amd64:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch arm \
            ${{ steps.tags.outputs.image }}:${{ matrix.tag  }} \
            ${{ steps.tags.outputs.manifest }}-arm:${{ steps.tags.outputs.tag }}
          docker manifest push ${{ steps.tags.outputs.image }}:${{ matrix.tag  }}
