name: Build go-server image for a target architecture
on:
  workflow_call:
    inputs:
      target:
        description: "Target architecture"
        required: true
        type: string
        default: "amd64"
jobs:
  build:
    runs-on: ${{ inputs.target }}
    steps:
      - name: Build target image
        run: |
          echo "Building image for target ${{ inputs.target }}"
