name: Build go-server image
on:
  release:
    types: [ created, edited ]
jobs:
  build-arm64:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tags
        id: tags
        run: |
          echo ::set-output name=arch::arm64
          echo ::set-output name=version::arm64
          echo ::set-output name=image::ghcr.io/${{ github.repository_owner }}/go-server-arm64
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}          
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build --tag ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }} --build-arg VERSION=1.23.2 --build-arg ARCH=${{ steps.tags.outputs.arch }} --build-arg PLATFORM=linux -f etc/docker/Dockerfile .
      - name: Push
        run: |
          docker push ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tags
        id: tags
        run: |
          echo ::set-output name=arch::amd64
          echo ::set-output name=image::ghcr.io/${{ github.repository_owner }}/go-server-amd64
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}          
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build --tag ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }} --build-arg VERSION=1.23.2 --build-arg ARCH=${{ steps.tags.outputs.arch }} --build-arg PLATFORM=linux -f etc/docker/Dockerfile .
      - name: Push
        run: |
          docker push ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
  manifest:
    needs:
      - build-amd64
      - build-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Set tags
        id: tags
        run: |
          echo ::set-output name=manifest::ghcr.io/${{ github.repository_owner }}/go-server
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}   
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Manifest
        run: |
          docker manifest create ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            --amend ${{ steps.tags.outputs.manifest }}-amd64:${{ steps.tags.outputs.tag }}
            --amend ${{ steps.tags.outputs.manifest }}-aarm64:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch arm64 ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            ${{ steps.tags.outputs.manifest }}-arm64:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch amd64 ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            ${{ steps.tags.outputs.manifest }}-amd64:${{ steps.tags.outputs.tag }}
          docker manifest push ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }}
  