name: Release
on:
  release:
    types: [ created ]
jobs:
  build-arm:
    runs-on: [self-hosted, linux, ARM]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'      
      - name: Build for Linux on ARM
        run: |
          make deb
      - name: Upload DEBs to release
        run: |
          TAG=`git describe --abbrev=0 --tags`
          gh release upload ${TAG} build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
